# Definición de los mensajes de la acción
# Goal: 
string name
uint32 questions
string difficulty
---
# Result: comprobacion fin
bool success
---
# Feedback: tiempo pasado y tiempo que queda
string currentTime